/*
  Warnings:

  - Added the required column `department` to the `provider` table without a default value. This is not possible if the table is not empty.

*/
-- CreateEnum
CREATE TYPE "department" AS ENUM ('EMERGENCY', 'ADMISSIONS', 'ANESTHETICS', 'BREAST_SCREENING', 'BURN_CENTER', 'CARDIOLOGY', 'CENTRAL_STERILE_SERVICES_DEPARTMENT', 'CHAPLAINCY', 'CORONARY_CARE_UNIT', 'CRITICAL_CARE', 'DIAGNOSTIC_IMAGING', 'DISCHARGE_LOUNGE', 'ELDERLY_SERVICES', 'FINANCE_DEPARTMENT', 'GASTROENTEROLOGY', 'GENERAL_SERVICES', 'GENERAL_SURGERY', 'GYNECOLOGY', 'HEMATOLOGY', 'HEALTH_AND_SAFETY', 'INTENSIVE_CARE_UNIT', 'HUMAN_RESOURCES', 'INFECTION_CONTROL', 'INFORMATION_MANAGEMENT', 'MATERNITY', 'MEDICAL_RECORDS', 'MICROBIOLOGY', 'NEONATAL', 'NEPHROLOGY', 'NEUROLOGY', 'NUTRITION_AND_DIETETICS', 'OCCUPATIONAL_THERAPY', 'ONCOLOGY', 'OPHTHALMOLOGY', 'ORTHOPEDICS', 'OTOLARYNGOLOGY', 'PAIN_MANAGEMENT', 'PATIENT_ACCOUNTS', 'PATIENT_SERVICES', 'PHARMACY', 'PHYSIOTHERAPY', 'PURCHASING_AND_SUPPLIES', 'RADIOLOGY', 'RADIOTHERAPY', 'RENAL', 'RHEUMATOLOGY', 'SEXUAL_HEALTH', 'SOCIAL_WORK', 'UROLOGY');

-- AlterTable
ALTER TABLE "provider" ADD COLUMN     "department" "department" NOT NULL;
